name: C++ checks

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
      pull-requests: read

    steps:
      - uses: actions/checkout@v4

      - name: C/C++ Linter
        uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files-changed-only: false
          lines-changed-only: ${{ github.event_name == 'pull_request' }}
          style: file
          tidy-checks: ''
          step-summary: true
